# Generated by Django 4.0.10 on 2023-07-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='mobile',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='image',
        ),
    ]
