# Generated by Django 4.0.10 on 2023-07-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_rename_mobile_admin_password_remove_admin_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marked_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='return_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
    ]
